"""Multi-product try-on runs.

POST /api/tryon/run              plan N products (ordered); nothing is generated yet
POST /api/tryon/run/{id}/next    execute the next planned step: exactly ONE FASHN generation per call
GET  /api/tryon/run/{id}         full tracking view

The plan is stored server-side before any step runs, so a selected product can never be dropped silently.
Step N starts from the raw result of step N-1. The first failed or rejected step stops the run and marks every
later step SKIPPED. Nothing is retried.

Honesty rules (what the words mean):
  generated   a FASHN result image exists for the step
  VERIFIED    OpenAI AND Gemini both analysed it and passed every check
  FINISHED    every planned step produced an image; says NOTHING about whether the products are in the image
  final       a separate whole-look check of the FINAL image against EVERY selected product decides what we claim
Mock results are always "SIMULATED": never verified, never "applied".
"""
import json

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from ..config import settings
from ..db import get_db
from ..models import Product, TryOnJob, TryOnResult, TryOnRun
from ..services.fashn.builder import CREDITS_PER_GENERATION
from ..services.fashn.guard import credits_spent, live_enabled, vto_mode
from ..services.storage import local as storage
from ..services.tryon import ACCEPTED, run_job
from ..services.verification.base import FinalContext, get_verifier, vision_models_configured
from .routes import _job_view

router = APIRouter(prefix="/api")
MAX_ITEMS = 8


class RunRequest(BaseModel):
    person_path: str
    product_ids: list[int]  # in application order


def _presence_label(step: dict) -> str:
    """What we can honestly say about 'is this product in the image?' from the per-step check."""
    if step["simulated"]:
        return "SIMULATED"
    res = step["result"]
    if not res:
        return "NOT_GENERATED"
    presence = res["verification"]["checks"].get("product_presence", "NOT_CHECKED")
    return {"PASS": "PRESENT", "FAIL": "ABSENT"}.get(presence, "REVIEW_REQUIRED")


def _final_status(run: TryOnRun, steps: list[dict], final: dict | None) -> str:
    if any(s["simulated"] for s in steps):
        return "SIMULATED"
    if run.status in ("PLANNED", "RUNNING"):
        return "IN_PROGRESS"
    if run.status == "STOPPED":
        return "STOPPED"
    return {"PASS": "VERIFIED", "FAIL": "FAILED"}.get(final["overall"] if final else "", "REVIEW_REQUIRED")


def _summary(run: TryOnRun, steps: list[dict], final: dict | None, status: str) -> str:
    n = len(steps)
    generated = sum(1 for s in steps if s["result"])
    if status == "SIMULATED":
        return ("MOCK / DEMO: simulated images only. Nothing was generated by FASHN and nothing was verified. "
                "This is NOT evidence that multi-product try-on works.")
    text = f"{generated} of {n} steps generated a FASHN image."
    if status == "STOPPED":
        bad = next((s for s in steps if s["status"] in ("FAILED", "REJECTED")), None)
        text += f" Stopped at step {bad['step']} ({bad['status'].lower()}); later steps were skipped." if bad else " Stopped."
    if final:
        present = sum(1 for i in final["items"] if i["present"] == "PASS" and i["matches"] == "PASS")
        text += (f" Final image checked by {' + '.join(final['performed_by']) or 'no model'}: "
                 f"{present} of {len(final['items'])} selected products confirmed present and matching; "
                 f"identity {final['identity_preserved'].replace('_', ' ').lower()}.")
    elif status == "REVIEW_REQUIRED":
        text += " The final image was NOT verified: manual review required."
    return text


def _run_view(db: Session, run: TryOnRun) -> dict:
    db.expire_all()
    jobs = db.query(TryOnJob).filter_by(run_id=run.id).order_by(TryOnJob.step).all()
    steps = []
    for j in jobs:
        v = _job_view(db, j)
        v["product_presence"] = _presence_label(v)
        steps.append(v)
    final = json.loads(run.final_verification_json) if run.final_verification_json else None
    status = _final_status(run, steps, final)
    accepted = [s for s in steps if s["status"] in ACCEPTED and s["result"]]
    return {
        "id": run.id, "status": run.status, "total_steps": len(steps), "person_url": f"/files/{run.person_image_path}",
        "simulated": any(s["simulated"] for s in steps),
        "steps": steps, "final_url": accepted[-1]["result"]["url"] if accepted else None,
        "final_status": status, "final_verification": final, "summary": _summary(run, steps, final, status),
        "credits_required": len(steps) * CREDITS_PER_GENERATION,
    }


@router.post("/tryon/run")
def create_run(req: RunRequest, db: Session = Depends(get_db)):
    if not req.product_ids:
        raise HTTPException(400, "select at least one product")
    if len(req.product_ids) > MAX_ITEMS:
        raise HTTPException(400, f"at most {MAX_ITEMS} products per run")
    if len(set(req.product_ids)) != len(req.product_ids):
        raise HTTPException(400, "the same product was selected twice")
    if not req.person_path.startswith("persons/") or ".." in req.person_path \
            or not storage.abs_path(req.person_path).is_file():
        raise HTTPException(400, "unknown person image")
    products = [db.get(Product, pid) for pid in req.product_ids]
    if any(p is None for p in products):
        raise HTTPException(404, "a selected product was not found")
    if live_enabled():
        # A real run must be really verified: both vision models are required, and verification cannot be disabled.
        if settings.verification_mode == "placeholder" or not vision_models_configured():
            raise HTTPException(400, "A live run requires real OpenAI + Gemini verification (both API keys, "
                                     "verification enabled). Nothing was started.")
        # never start a paid chain that cannot finish under the credit budget
        need = len(products) * CREDITS_PER_GENERATION
        left = settings.fashn_credit_cap - credits_spent(db)
        if need > left:
            raise HTTPException(400, f"{len(products)} live generations need {need} credits but only "
                                     f"{max(left, 0)} remain in the budget. Nothing was started.")
    run = TryOnRun(person_image_path=req.person_path, status="PLANNED")
    db.add(run)
    db.commit()
    prev_id = None
    for i, p in enumerate(products, start=1):
        job = TryOnJob(run_id=run.id, product_id=p.id, step=i, parent_job_id=prev_id, status="PLANNED",
                       provider=vto_mode(), person_image_path=req.person_path,
                       person_image_sha256=req.person_path.split("/")[-1].split(".")[0])
        db.add(job)
        db.commit()
        prev_id = job.id
    return _run_view(db, run)


async def _final_verification(db: Session, run: TryOnRun, jobs: list[TryOnJob]) -> None:
    """Whole-look check of the FINAL image against every selected product. Never runs on mock output."""
    if any(j.provider == "mock" for j in jobs):
        return
    last = jobs[-1]
    pres = db.query(TryOnResult).filter_by(job_id=last.id).first()
    try:
        ctx = FinalContext(
            original=storage.read_bytes(run.person_image_path), result=storage.read_bytes(pres.result_path),
            products=[((p := db.get(Product, j.product_id)).name, p.category, storage.read_bytes(p.image_path))
                      for j in jobs])
        final = await get_verifier(last.provider).verify_final(ctx)
    except Exception as e:  # an outage must never turn into a PASS
        final = {"overall": "REVIEW_REQUIRED", "identity_preserved": "REVIEW_REQUIRED", "items": [], "models": {},
                 "performed_by": [], "notes": f"final verification unavailable ({type(e).__name__})"}
    if final is not None:
        run.final_verification_json = json.dumps(final)
        db.commit()


@router.post("/tryon/run/{run_id}/next")
async def run_next(run_id: int, db: Session = Depends(get_db)):
    run = db.get(TryOnRun, run_id)
    if not run:
        raise HTTPException(404, "run not found")
    if run.status in ("FINISHED", "STOPPED"):
        raise HTTPException(400, f"run is already {run.status}")
    jobs = db.query(TryOnJob).filter_by(run_id=run.id).order_by(TryOnJob.step).all()
    idx = next((i for i, j in enumerate(jobs) if j.status == "PLANNED"), None)
    if idx is None:
        run.status = "FINISHED"
        db.commit()
        return _run_view(db, run)
    job = jobs[idx]

    def stop_run(from_idx: int, reason: str):
        for j in jobs[from_idx:]:
            if j.status == "PLANNED":
                j.status, j.error = "SKIPPED", reason
        run.status = "STOPPED"
        db.commit()

    if idx > 0:  # base image = raw result of the previous step
        prev = jobs[idx - 1]
        pres = db.query(TryOnResult).filter_by(job_id=prev.id).first()
        if prev.status not in ACCEPTED or not pres:
            stop_run(idx, f"skipped: step {prev.step} did not finish")
            return _run_view(db, run)
        job.person_image_path = pres.result_path
        job.person_image_sha256 = pres.result_sha256
    run.status = "RUNNING"
    db.commit()

    await run_job(job.id)  # exactly one generation; awaited inline, never in the background
    db.refresh(job)
    if job.status not in ACCEPTED:
        stop_run(idx + 1, f"skipped: step {job.step} {job.status.lower()}")
    elif all(j.status in ACCEPTED for j in jobs):
        run.status = "FINISHED"  # every step produced an image; quality is decided by the final verification
        db.commit()
        await _final_verification(db, run, jobs)
    return _run_view(db, run)


@router.get("/tryon/run/{run_id}")
def get_run(run_id: int, db: Session = Depends(get_db)):
    run = db.get(TryOnRun, run_id)
    if not run:
        raise HTTPException(404, "run not found")
    return _run_view(db, run)
